default: &default
   adapter: sqlite3
   pool: 5
   timeout: 5000

development:
   <<: *default
   database: db/development.sqlite3
   adapter: sqlite3
   pool: 5
   timeout: 5000

test:
   <<: *default
   database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  pool: 5
  timeout: 5000
